import { flushPromises, mount } from '@vue/test-utils'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import BuiltinAdapterLogin from '../BuiltinAdapterLogin.vue'

const { start, complete, cancel, getView } = vi.hoisted(() => ({ start: vi.fn(), complete: vi.fn(), cancel: vi.fn(), getView: vi.fn() }))
vi.mock('@/api/admin/builtinAdapters', () => ({ startBuiltinLogin: start, completeBuiltinLogin: complete, cancelBuiltinLogin: cancel, getBuiltinLoginView: getView }))
vi.mock('vue-i18n', async () => ({ ...await vi.importActual('vue-i18n'), useI18n: () => ({ t: (key: string) => key }) }))

const pending = (mode: 'poll' | 'callback') => ({ session_id: 'abc', mode, status: 'pending', auth_url: 'https://example.com/login', expires_at: Date.now() + 600000 })

describe('BuiltinAdapterLogin', () => {
  beforeEach(() => {
    vi.useFakeTimers()
    vi.clearAllMocks()
    cancel.mockResolvedValue(undefined)
    getView.mockResolvedValue(new Blob(['png'], { type: 'image/png' }))
    Object.defineProperty(URL, 'createObjectURL', { configurable: true, value: vi.fn(() => 'blob:deepseek-login') })
    Object.defineProperty(URL, 'revokeObjectURL', { configurable: true, value: vi.fn() })
  })
  afterEach(() => { vi.useRealTimers() })

  it('logs in to Arena with email and password, then returns the prepared model', async () => {
    start.mockResolvedValue({ ...pending('poll'), auth_url: undefined })
    const result = { ...pending('poll'), status: 'completed', account: { uid: 'user@example.com', model_id: 'arena-session-new' } }
    complete.mockResolvedValue(result)
    const wrapper = mount(BuiltinAdapterLogin, { props: { platform: 'arena' } })
    expect(wrapper.get('button').attributes('disabled')).toBeDefined()
    await wrapper.get('#arena-login-email').setValue('user@example.com')
    await wrapper.get('#arena-login-password').setValue(' private password ')
    await wrapper.get('button').trigger('click')
    await flushPromises()
    expect(start).toHaveBeenCalledWith('arena', expect.any(AbortSignal), { email: 'user@example.com', password: ' private password ' })
    expect((wrapper.get('#arena-login-password').element as HTMLInputElement).value).toBe('')
    expect(wrapper.find('a').exists()).toBe(false)
    expect(wrapper.text()).toContain('admin.accounts.arena.loggingIn')
    await vi.advanceTimersByTimeAsync(2500)
    await flushPromises()
    expect(wrapper.emitted('authorized')).toEqual([[result]])
    wrapper.unmount()
  })

  it('cancels Arena login on close and allows retry after a failed poll', async () => {
    start.mockResolvedValue({ ...pending('poll'), auth_url: undefined })
    complete.mockRejectedValue(new Error('upstream details'))
    const wrapper = mount(BuiltinAdapterLogin, { props: { platform: 'arena' } })
    await wrapper.get('#arena-login-email').setValue('user@example.com')
    await wrapper.get('#arena-login-password').setValue('secret')
    await wrapper.get('button').trigger('click')
    await flushPromises()
    await vi.advanceTimersByTimeAsync(2500)
    await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toBe('admin.accounts.arena.loginFailed')
    expect(cancel).toHaveBeenCalledWith('arena', 'abc')
    await wrapper.get('#arena-login-password').setValue('new-secret')
    await wrapper.get('button').trigger('click')
    await flushPromises()
    wrapper.unmount()
    await flushPromises()
    expect(cancel).toHaveBeenCalledTimes(2)
    expect(wrapper.emitted('authorized')).toBeUndefined()
  })

  it.each([
    ['ARENA_ACCESS_BLOCKED', 'accessBlocked'],
    ['ARENA_VERIFICATION_REQUIRED', 'verificationRequired'],
    ['ARENA_INVALID_CREDENTIALS', 'invalidCredentials'],
    ['ARENA_SESSION_UNUSABLE', 'sessionUnusable'],
    ['ARENA_SESSION_NOT_READY', 'sessionNotReady'],
    ['ARENA_BROWSER_UNAVAILABLE', 'browserUnavailable'],
    ['ARENA_NETWORK_ERROR', 'networkError'],
    ['ARENA_LOGIN_TIMEOUT', 'loginTimeout'],
    ['ARENA_SESSION_PREPARE_FAILED', 'sessionPrepareFailed'],
    ['BUILTIN_ADAPTER_DISABLED', 'unavailable'],
    ['ADAPTER_LOGIN_FAILED', 'loginFailed'],
    ['UNKNOWN_CODE', 'loginFailed'],
    ['toString', 'loginFailed']
  ])('shows static Arena guidance for %s without exposing upstream details', async (code, translationKey) => {
    const upstreamMessage = 'password=private-secret; session_token=private-token'
    start.mockRejectedValue({ code, message: upstreamMessage })
    const wrapper = mount(BuiltinAdapterLogin, { props: { platform: 'arena' } })
    await wrapper.get('#arena-login-email').setValue('user@example.com')
    await wrapper.get('#arena-login-password').setValue('private-secret')
    await wrapper.get('button').trigger('click')
    await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toBe(`admin.accounts.arena.${translationKey}`)
    expect(wrapper.text()).not.toContain(upstreamMessage)
    expect(wrapper.text()).not.toContain('private-secret')
    expect(wrapper.text()).not.toContain('private-token')
    expect((wrapper.get('#arena-login-password').element as HTMLInputElement).value).toBe('')
    expect(wrapper.emitted('authorized')).toBeUndefined()
    wrapper.unmount()
  })

  it('shows server access guidance and cancels polling when Arena session preparation is blocked', async () => {
    start.mockResolvedValue({ ...pending('poll'), auth_url: undefined })
    complete.mockRejectedValue({ code: 'ARENA_ACCESS_BLOCKED', message: 'session_token=private-token' })
    const wrapper = mount(BuiltinAdapterLogin, { props: { platform: 'arena' } })
    await wrapper.get('#arena-login-email').setValue('user@example.com')
    await wrapper.get('#arena-login-password').setValue('private-secret')
    await wrapper.get('button').trigger('click')
    await flushPromises()
    await vi.advanceTimersByTimeAsync(2500)
    await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toBe('admin.accounts.arena.accessBlocked')
    expect(wrapper.text()).not.toContain('private-token')
    expect(cancel).toHaveBeenCalledWith('arena', 'abc')
    expect(wrapper.emitted('authorized')).toBeUndefined()
    await vi.advanceTimersByTimeAsync(10000)
    expect(complete).toHaveBeenCalledTimes(1)
    wrapper.unmount()
  })

  it('fixes the selected ZCode plan and provider for the authorization session', async () => {
    start.mockResolvedValue(pending('poll'))
    complete.mockResolvedValue({ ...pending('poll'), status: 'completed', account: { uid: 'zcode-user' } })
    const wrapper = mount(BuiltinAdapterLogin, { props: { platform: 'zcode' } })
    await wrapper.get('#zcode-login-plan').setValue('start-plan')
    await wrapper.get('#zcode-login-provider').setValue('bigmodel')
    await wrapper.get('button').trigger('click')
    await flushPromises()
    expect(start).toHaveBeenCalledWith('zcode', expect.any(AbortSignal), { plan: 'start-plan', provider: 'bigmodel' })
    expect(wrapper.get('#zcode-login-plan').attributes('disabled')).toBeDefined()
    expect(wrapper.get('#zcode-login-provider').attributes('disabled')).toBeDefined()
    expect(wrapper.text()).toContain('admin.accounts.builtinLogin.zcodePoolHint')
    expect(wrapper.find('input').exists()).toBe(false)
    await vi.advanceTimersByTimeAsync(2500)
    await flushPromises()
    expect(complete).toHaveBeenCalledWith('zcode', expect.objectContaining({ mode: 'poll' }), '', expect.any(AbortSignal))
    expect(wrapper.emitted('authorized')).toHaveLength(1)
    wrapper.unmount()
  })

  it('imports VibeX credentials without polling and clears the input after success', async () => {
    start.mockResolvedValue(pending('callback'))
    complete.mockResolvedValue({ ...pending('callback'), status: 'completed', account: { uid: 'v1' } })
    const wrapper = mount(BuiltinAdapterLogin, { props: { platform: 'vibex' } })
    await wrapper.get('button').trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('admin.accounts.builtinLogin.vibexPoolHint')
    expect(wrapper.get('input').attributes('type')).toBe('password')
    await wrapper.get('input').setValue('test-vibex-token')
    await wrapper.get('button.btn-primary').trigger('click')
    await flushPromises()
    expect(complete).toHaveBeenCalledWith('vibex', expect.anything(), 'test-vibex-token', expect.any(AbortSignal))
    expect(wrapper.find('input').exists()).toBe(false)
    await vi.advanceTimersByTimeAsync(5000)
    expect(complete).toHaveBeenCalledTimes(1)
    wrapper.unmount()
  })

  it('signs in to DeepSeek with email and password, then completes automatically', async () => {
    start.mockResolvedValue(pending('poll'))
    const result = { ...pending('poll'), status: 'completed', account: { uid: 'deepseek-user', auto_relogin: true } }
    complete.mockResolvedValue(result)
    const wrapper = mount(BuiltinAdapterLogin, { props: { platform: 'deepseek_web' } })
    expect(wrapper.text()).toContain('admin.accounts.builtinLogin.deepseekWebStart')
    expect(wrapper.get('button').attributes('disabled')).toBeDefined()
    expect((wrapper.get('#deepseek-auto-relogin').element as HTMLInputElement).checked).toBe(true)
    expect(wrapper.text()).toContain('admin.accounts.builtinLogin.deepseekWebAutoReloginHint')
    expect(wrapper.find('[data-testid="deepseek-auto-relogin-status"]').exists()).toBe(false)
    await wrapper.get('#deepseek-login-email').setValue('user@example.com')
    await wrapper.get('#deepseek-login-password').setValue('password')
    await wrapper.get('button').trigger('click')
    await flushPromises()
    expect(start).toHaveBeenCalledWith('deepseek_web', expect.any(AbortSignal), { email: 'user@example.com', password: 'password', auto_relogin: true })
    expect((wrapper.get('#deepseek-login-password').element as HTMLInputElement).value).toBe('')
    expect(wrapper.get('#deepseek-auto-relogin').attributes('disabled')).toBeDefined()
    expect(wrapper.get('#deepseek-login-email').attributes('disabled')).toBeDefined()
    expect(wrapper.get('#deepseek-login-password').attributes('disabled')).toBeDefined()
    expect(wrapper.text()).toContain('admin.accounts.builtinLogin.deepseekWebHint')
    expect(wrapper.text()).not.toContain('admin.accounts.builtinLogin.deepseek_webHint')
    expect(wrapper.find('a').exists()).toBe(false)
    expect(getView).toHaveBeenCalledWith('deepseek_web', 'abc', expect.any(AbortSignal))
    expect(wrapper.get('[data-testid="deepseek-login-view"]').attributes('src')).toBe('blob:deepseek-login')
    expect(wrapper.text()).toContain('admin.accounts.builtinLogin.deepseekWebWaiting')
    expect(wrapper.find('#deepseek-web-token').exists()).toBe(false)
    expect(wrapper.find('#deepseek-web-device').exists()).toBe(false)
    await vi.advanceTimersByTimeAsync(2500)
    await flushPromises()
    expect(complete).toHaveBeenCalledWith('deepseek_web', expect.anything(), '', expect.any(AbortSignal))
    expect(wrapper.emitted('authorized')).toHaveLength(1)
    expect(wrapper.get('[data-testid="deepseek-auto-relogin-status"]').text()).toBe('admin.accounts.builtinLogin.deepseekWebAutoReloginEnabled')
    expect(wrapper.get('#deepseek-auto-relogin').attributes('disabled')).toBeUndefined()
    await wrapper.get('#deepseek-auto-relogin').setValue(false)
    expect(wrapper.get('[data-testid="deepseek-auto-relogin-status"]').text()).toBe('admin.accounts.builtinLogin.deepseekWebAutoReloginEnabled')
    expect(start).toHaveBeenCalledTimes(1)
    expect(wrapper.get('button').attributes('disabled')).toBeDefined()
    wrapper.unmount()
  })

  it.each([false, true])('submits auto-relogin selection %s and shows the saved server setting', async (selected) => {
    start.mockResolvedValue(pending('poll'))
    complete.mockResolvedValue({ ...pending('poll'), status: 'completed', account: { uid: 'deepseek-user', auto_relogin: false } })
    const wrapper = mount(BuiltinAdapterLogin, { props: { platform: 'deepseek_web' } })
    await wrapper.get('#deepseek-login-email').setValue('user@example.com')
    await wrapper.get('#deepseek-login-password').setValue('password')
    await wrapper.get('#deepseek-auto-relogin').setValue(selected)
    await wrapper.get('button').trigger('click')
    await flushPromises()
    expect(start).toHaveBeenCalledWith('deepseek_web', expect.any(AbortSignal), { email: 'user@example.com', password: 'password', auto_relogin: selected })
    await vi.advanceTimersByTimeAsync(2500)
    await flushPromises()
    expect(wrapper.get('[data-testid="deepseek-auto-relogin-status"]').text()).toBe('admin.accounts.builtinLogin.deepseekWebAutoReloginDisabled')
    expect((wrapper.get('#deepseek-login-password').element as HTMLInputElement).value).toBe('')
    wrapper.unmount()
  })

  it('does not claim automatic sign-in is enabled without confirmation from the server', async () => {
    start.mockResolvedValue(pending('poll'))
    complete.mockResolvedValue({ ...pending('poll'), status: 'completed', account: { uid: 'deepseek-user' } })
    const wrapper = mount(BuiltinAdapterLogin, { props: { platform: 'deepseek_web' } })
    await wrapper.get('#deepseek-login-email').setValue('user@example.com')
    await wrapper.get('#deepseek-login-password').setValue('password')
    await wrapper.get('button').trigger('click')
    await flushPromises()
    await vi.advanceTimersByTimeAsync(2500)
    await flushPromises()
    expect(wrapper.emitted('authorized')).toHaveLength(1)
    expect(wrapper.find('[data-testid="deepseek-auto-relogin-status"]').exists()).toBe(false)
    wrapper.unmount()
  })

  it('explains when the DeepSeek web adapter is not enabled', async () => {
    start.mockRejectedValue({ code: 'BUILTIN_ADAPTER_DISABLED', message: 'Enable the built-in adapter and configure its shared key first' })
    const wrapper = mount(BuiltinAdapterLogin, { props: { platform: 'deepseek_web' } })
    await wrapper.get('#deepseek-login-email').setValue('user@example.com')
    await wrapper.get('#deepseek-login-password').setValue('password')
    await wrapper.get('button').trigger('click')
    await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toBe('admin.accounts.builtinLogin.deepseekWebUnavailable')
    expect((wrapper.get('#deepseek-login-password').element as HTMLInputElement).value).toBe('')
    expect(wrapper.find('[data-testid="deepseek-auto-relogin-status"]').exists()).toBe(false)
    wrapper.unmount()
  })

  it('submits the TRAE callback and clears credentials after success', async () => {
    start.mockResolvedValue(pending('callback'))
    complete.mockResolvedValue({ ...pending('callback'), status: 'completed', account: { uid: 'u1' } })
    const wrapper = mount(BuiltinAdapterLogin, { props: { platform: 'traework' } })
    await wrapper.get('button').trigger('click'); await flushPromises()
    expect(wrapper.get('a').attributes('href')).toBe('https://example.com/login')
    await wrapper.get('input').setValue('http://127.0.0.1:18080/authorize?refreshToken=secret')
    await wrapper.get('button.btn-primary').trigger('click'); await flushPromises()
    expect(complete).toHaveBeenCalledWith('traework', expect.anything(), expect.stringContaining('refreshToken=secret'), expect.any(AbortSignal))
    expect(wrapper.text()).toContain('admin.accounts.builtinLogin.success')
    expect(wrapper.find('input').exists()).toBe(false)
    expect(wrapper.emitted('authorized')).toHaveLength(1)
    wrapper.unmount()
  })

  it('polls WorkBuddy and stops after success', async () => {
    start.mockResolvedValue(pending('poll'))
    complete.mockResolvedValueOnce(pending('poll')).mockResolvedValueOnce({ ...pending('poll'), status: 'completed', account: { uid: 'u2' } })
    const wrapper = mount(BuiltinAdapterLogin, { props: { platform: 'workbuddy' } })
    await wrapper.get('button').trigger('click'); await flushPromises()
    expect(wrapper.find('input').exists()).toBe(false)
    await vi.advanceTimersByTimeAsync(5000); await flushPromises()
    expect(complete).toHaveBeenCalledTimes(2)
    await vi.advanceTimersByTimeAsync(10000)
    expect(complete).toHaveBeenCalledTimes(2)
    expect(wrapper.emitted('authorized')).toHaveLength(1)
    wrapper.unmount()
  })

  it('does not leave polling active after unmount', async () => {
    start.mockResolvedValue(pending('poll'))
    const wrapper = mount(BuiltinAdapterLogin, { props: { platform: 'workbuddy' } })
    await wrapper.get('button').trigger('click'); await flushPromises()
    wrapper.unmount(); await vi.advanceTimersByTimeAsync(10000)
    expect(complete).not.toHaveBeenCalled()
  })

  it('shows errors and permits a new authorization', async () => {
    start.mockRejectedValue(new Error('Adapter unavailable'))
    const wrapper = mount(BuiltinAdapterLogin, { props: { platform: 'workbuddy' } })
    await wrapper.get('button').trigger('click'); await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toBe('Adapter unavailable')
    expect(wrapper.get('button').attributes('disabled')).toBeUndefined()
    wrapper.unmount()
  })
})
