import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { build } from 'esbuild';

const output = await build({ entryPoints: ['src/install.ts'], bundle: true, platform: 'node', format: 'esm', write: false });
const { codexConfigDir, detectPlatform, planClientInstall, resolveDirectory, windowsInstallScript } = await import('data:text/javascript;base64,' + Buffer.from(output.outputFiles[0].text).toString('base64'));
const setupOutput = await build({ entryPoints: ['../../frontend/src/utils/codexSetup.ts'], bundle: true, platform: 'node', format: 'esm', write: false });
const { buildCodexSetupCommand, defaultCodexSetupOptions } = await import('data:text/javascript;base64,' + Buffer.from(setupOutput.outputFiles[0].text).toString('base64'));

test('Windows data directories accept both D and G drives without a default drive', () => {
  for (const drive of ['D', 'G']) {
    assert.equal(codexConfigDir('win32', `${drive}:\\Codex\\data`), `${drive}:\\Codex\\data`);
  }
});

test('path resolution uses the requested platform instead of the CI host platform', () => {
  assert.equal(resolveDirectory('/mnt/AI tools', 'linux'), '/mnt/AI tools');
  assert.equal(resolveDirectory('/Volumes/Data/AI apps', 'darwin'), '/Volumes/Data/AI apps');
  assert.equal(resolveDirectory('G:/Codex/data', 'win32'), 'G:\\Codex\\data');
});

test('Windows CMD preserves G drive arguments generated by the frontend', { skip: process.platform !== 'win32' }, () => {
  const sandbox = mkdtempSync(join(tmpdir(), 'sub2api-cmd-'));
  try {
    writeFileSync(join(sandbox, 'npx.cmd'), `@echo off\r\n@"${process.execPath}" -e "console.log(JSON.stringify(process.argv.slice(1)))" -- %*\r\n`);
    for (const directory of ['G:\\Codex\\data', "G:\\AI tools\\O'Brien", 'G:\\']) {
      const command = buildCodexSetupCommand('https://example.com', 'sk-test', { ...defaultCodexSetupOptions(), codexHome: directory }, true);
      const result = spawnSync('cmd.exe', ['/d', '/s', '/c', command], { cwd: sandbox, encoding: 'utf8' });
      assert.ifError(result.error);
      assert.equal(result.status, 0, result.stdout + result.stderr);
      assert.deepEqual(JSON.parse(result.stdout), ['-y', 'sub2api-codex-setup', '--base-url', 'https://example.com', '--api-key', 'sk-test', '--codex-home', directory, '--persist-home']);
    }
  } finally {
    rmSync(sandbox, { recursive: true, force: true, maxRetries: 3 });
  }
});

test('Windows desktop selects a Windows installer and never downloads a DMG', (context) => {
  assert.equal(detectPlatform('win32'), 'windows');
  const plan = planClientInstall({ platform: 'win32' });
  assert.equal(plan.platform, 'windows');
  assert.equal(plan.supported, true);
  if (plan.installed) {
    context.skip('Desktop app is already installed');
    return;
  }
  assert.equal(plan.install[0].command, 'powershell.exe');
  assert.match(plan.install[0].args.at(-1), /get\.microsoft\.com\/installer\/download\/9PLM9XGG6VKS/);
  assert.doesNotMatch(JSON.stringify(plan.install), /Codex\.dmg|hdiutil|\bbash\b/);
});

for (const scenario of [
  { name: 'desktop installer succeeds', installerExit: 0, downloadError: false, exit: 0, fallback: false },
  { name: 'download fails and CLI fallback succeeds', downloadError: true, npmExit: 0, exit: 0, fallback: true },
  { name: 'desktop installer fails and CLI fallback succeeds', installerExit: 8, npmExit: 0, exit: 0, fallback: true },
  { name: 'CLI fallback also fails', downloadError: true, npmExit: 9, exit: 1, fallback: true }
]) {
  test('Windows desktop execution when ' + scenario.name, { skip: process.platform !== 'win32' }, () => {
    const mocks = `
function Invoke-WebRequest {
  param([switch]$UseBasicParsing, $Uri, $OutFile)
  Write-Host ('DOWNLOAD:' + $OutFile)
  if ($Uri -ne 'https://get.microsoft.com/installer/download/9PLM9XGG6VKS') { throw 'Unexpected installer URL' }
  ${scenario.downloadError ? "throw 'Download failed'" : "[IO.File]::WriteAllText($OutFile, 'mock installer')"}
}
function Start-Process {
  param($FilePath, [switch]$PassThru)
  if (-not $PassThru -or -not (Test-Path -LiteralPath $FilePath)) { throw 'Invalid installer execution' }
  Write-Host 'INSTALLER'
  [PSCustomObject]@{ ExitCode = ${scenario.installerExit || 0}; WaitForExit = { param($ms) $true } }
}
function Get-Command { param($Name, $ErrorAction) [PSCustomObject]@{ Source = 'npm.cmd' } }
function npm.cmd { $global:LASTEXITCODE = ${scenario.npmExit || 0}; Write-Host 'NPM' }
`;
    const result = spawnSync('powershell.exe', ['-NoProfile', '-Command', mocks + windowsInstallScript()], { encoding: 'utf8' });
    assert.ifError(result.error);
    assert.equal(result.status, scenario.exit, result.stdout + result.stderr);
    assert.equal(result.stdout.includes('DOWNLOAD:'), true);
    assert.equal(result.stdout.includes('INSTALLER'), !scenario.downloadError);
    assert.equal(result.stdout.includes('NPM'), scenario.fallback);
    const download = result.stdout.match(/DOWNLOAD:([^\r\n]+)/)?.[1];
    if (download) {
      assert.equal(existsSync(dirname(download)), false, 'temporary installer directory must be removed');
    }
  });
}

test('Windows CLI installs in a quoted custom prefix with its own npm cache', () => {
  const plan = planClientInstall({ platform: 'win32', client: 'cli', installDir: "D:\\AI tools\\O'Brien" });
  const script = plan.install[0].args.at(-1);
  assert.equal(plan.install[0].command, 'powershell.exe');
  assert.ok(script.includes("'--prefix' 'D:\\AI tools\\O''Brien'"));
  assert.ok(script.includes("'--cache' 'D:\\AI tools\\O''Brien\\npm-cache'"));
  assert.match(script, /exit \$LASTEXITCODE/);
});

test('Store desktop installation rejects an unsupported custom directory', () => {
  assert.throws(() => planClientInstall({ platform: 'win32', installDir: 'D:\\Codex' }), /--client cli/);
});

test('Linux CLI installation is supported and keeps spaces in a single argument', () => {
  const plan = planClientInstall({ platform: 'linux', client: 'cli', installDir: '/mnt/AI tools' });
  assert.equal(plan.supported, true);
  assert.deepEqual(plan.install, [{ command: 'npm', args: ['install', '--global', '@openai/codex', '--registry=https://registry.npmmirror.com', '--prefix', '/mnt/AI tools', '--cache', '/mnt/AI tools/npm-cache'] }]);
});

test('macOS desktop honors a requested app directory instead of skipping another installation', () => {
  const plan = planClientInstall({ platform: 'darwin', installDir: '/Volumes/Data/AI apps' });
  assert.equal(plan.installed, false);
  assert.ok(plan.install[0].args[1].includes("target_dir='/Volumes/Data/AI apps'"));
});

test('desktop installers prefer the gateway cache when baseUrl is supplied', () => {
  const mac = planClientInstall({ platform: 'darwin', baseUrl: 'https://gateway.example/v1' });
  assert.match(mac.install[0].args[1], /gateway\.example\/downloads\/Codex\.dmg/);
  assert.match(mac.install[0].args[1], /persistent\.oaistatic\.com\/codex-app-prod\/Codex\.dmg/);

  const win = planClientInstall({ platform: 'win32', baseUrl: 'https://gateway.example/v1' });
  assert.match(win.install[0].args.at(-1), /gateway\.example\/downloads\/ChatGPT-Installer\.exe/);
  assert.match(win.install[0].args.at(-1), /get\.microsoft\.com\/installer\/download\/9PLM9XGG6VKS/);
});

test('ambiguous Windows drive-relative paths fail validation', () => {
  for (const path of ['D:Codex', '\\Codex', 'relative', 'D:\\bad\npath']) {
    assert.throws(() => resolveDirectory(path, 'win32'));
  }
  assert.equal(resolveDirectory('D:/AI tools/data', 'win32'), 'D:\\AI tools\\data');
});
